stages:
  - build
  - test
  - sonarqube
build:
  stage: build
  script: "mvn compile"
test:
  stage: test
  script: "mvn test"
  dependencies:
    - build
sonarqube:
  stage: sonarqube
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar "-Dsonar.qualitygate.wait=true"
  allow_failure: true
  only:
    - merge_requests
    - master
    - develop
  dependencies:
    - test
